<div><img src="mod/Bienes/img/cesta_basura.png"> Cesta de basura</div>
<div><img src="mod/Bienes/img/reflector.png"> Reflector</div>
<div><img src="mod/Bienes/img/luminaria.png"> Luminaria</div>
<div><img src="mod/Bienes/img/sumidero.png"> Sumidero</div>
<div><img src="mod/Bienes/img/pino.png"> Pino</div>
<div><img src="mod/Bienes/img/hidrante.png"> Hidrante</div>
<div><img src="mod/Bienes/img/arbol.png"> &Aacute;rbol</div>
<div><img src="mod/Bienes/img/palma.png"> Palma</div>
<div><img src="mod/Bienes/img/poste.png"> Poste</div>
<div><img src="mod/Bienes/img/camara.png"> C&aacute;mara</div>